    - name: Clean repository except workflows and README
      run: |
        mkdir temp
        mv .github/workflows temp/
        mv README.md temp/  # Add this line to preserve README
        rm -rf ./*
        mv temp/workflows .github/
        mv temp/README.md ./
        rm -rf temp
``` ​​​​​​​​​​​​​​​​​​​​​​​​​​​​​​​​​​​​​​​​​​​​​​​​​​