name: Clean repository

on: 
  push:
    branches:
      - main

jobs:
  clean-repo:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Clean repository
        run: |
          rm -rf ./*